// <auto-generated />
using System;
using BatchIQ.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BatchIQ.Persistence.Migrations
{
    [DbContext(typeof(BatchIQDbContext))]
    [Migration("20250709005502_ProcessManufacturingSupport")]
    partial class ProcessManufacturingSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BatchIQ.Domain.Entities.BatchInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseQuantityUsed")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityUsed")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SourceBatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionBatchId");

                    b.HasIndex("SourceBatchNumber");

                    b.HasIndex("SourceLocationId");

                    b.ToTable("BatchInputs", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.BatchOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseQuantityProduced")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CostPerUnit")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int?>("DestinationLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QualityGrade")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityProduced")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QuantityVariance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalAllocatedCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("YieldPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionBatchId");

                    b.HasIndex("QualityGrade");

                    b.ToTable("BatchOutputs", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductionTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionTransactionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("TransactionType");

                    b.HasIndex("FromLocationId", "ToLocationId");

                    b.HasIndex("ProductId", "Timestamp");

                    b.ToTable("InventoryTransactions", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProcessTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedYieldPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QualityCheckpoints")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StandardProcessingTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProcessTemplates");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProcessTemplateInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StandardQuantity")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StandardUnit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessTemplateId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProcessTemplateInputs");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProcessTemplateOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpectedYieldPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessTemplateId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProcessTemplateOutputs");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<string>("BrandEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandFa")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManufactured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsProcessedProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ProductType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.Property<decimal>("SizeValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UnitType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.HasIndex("IsManufactured");

                    b.HasIndex("IsProcessedProduct");

                    b.HasIndex("ProductType");

                    b.HasIndex("NameEn", "BrandEn");

                    b.HasIndex("NameFa", "BrandFa");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductBOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostPerUnit")
                        .HasColumnType("decimal(12,4)");

                    b.Property<bool>("IsCritical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityRequired")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.HasIndex("ComponentProductId");

                    b.HasIndex("IsCritical");

                    b.HasIndex("ParentProductId");

                    b.HasIndex("Sequence");

                    b.HasIndex("ParentProductId", "ComponentProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductBOM_Parent_Component");

                    b.ToTable("ProductBOMs", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCodes", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductionBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ProcessingCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("SupervisorId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalInputCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("YieldEfficiency")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("ProcessType");

                    b.HasIndex("ProductionDate");

                    b.HasIndex("Status");

                    b.HasIndex("ProcessType", "ProductionDate");

                    b.ToTable("ProductionBatches", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductionTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseQuantityProduced")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ProductionCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityProduced")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("SupervisorId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalMaterialCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Unit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionDate");

                    b.HasIndex("Status");

                    b.HasIndex("ProductId", "ProductionDate");

                    b.HasIndex("Status", "ProductionDate");

                    b.ToTable("ProductionTransactions", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.BatchInput", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany("UsedAsInput")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.ProductionBatch", "ProductionBatch")
                        .WithMany("Inputs")
                        .HasForeignKey("ProductionBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.Location", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("ProductionBatch");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.BatchOutput", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany("ProducedAsOutput")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.ProductionBatch", "ProductionBatch")
                        .WithMany("Outputs")
                        .HasForeignKey("ProductionBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationLocation");

                    b.Navigation("Product");

                    b.Navigation("ProductionBatch");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Location", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.ProductionTransaction", "ProductionTransaction")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductionTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BatchIQ.Domain.Entities.Location", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromLocation");

                    b.Navigation("Product");

                    b.Navigation("ProductionTransaction");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Location", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Location", "ParentLocation")
                        .WithMany("Children")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProcessTemplateInput", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.ProcessTemplate", "ProcessTemplate")
                        .WithMany("ExpectedInputs")
                        .HasForeignKey("ProcessTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessTemplate");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProcessTemplateOutput", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.ProcessTemplate", "ProcessTemplate")
                        .WithMany("ExpectedOutputs")
                        .HasForeignKey("ProcessTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessTemplate");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductBOM", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Product", "ComponentProduct")
                        .WithMany("UsedInProducts")
                        .HasForeignKey("ComponentProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.Product", "ParentProduct")
                        .WithMany("Components")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentProduct");

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductCode", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany("Codes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductionBatch", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductionTransaction", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Location", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProcessTemplate", b =>
                {
                    b.Navigation("ExpectedInputs");

                    b.Navigation("ExpectedOutputs");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Product", b =>
                {
                    b.Navigation("Codes");

                    b.Navigation("Components");

                    b.Navigation("ProducedAsOutput");

                    b.Navigation("UsedAsInput");

                    b.Navigation("UsedInProducts");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductionBatch", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductionTransaction", b =>
                {
                    b.Navigation("InventoryTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
