// <auto-generated />
using System;
using BatchIQ.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BatchIQ.Persistence.Migrations
{
    [DbContext(typeof(BatchIQDbContext))]
    [Migration("20250708230255_EnhancedInventoryAndProductionManagement")]
    partial class EnhancedInventoryAndProductionManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BatchIQ.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductionTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionTransactionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("TransactionType");

                    b.HasIndex("FromLocationId", "ToLocationId");

                    b.HasIndex("ProductId", "Timestamp");

                    b.ToTable("InventoryTransactions", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<string>("BrandEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandFa")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManufactured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ProductType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.Property<decimal>("SizeValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UnitType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.HasIndex("IsManufactured");

                    b.HasIndex("ProductType");

                    b.HasIndex("NameEn", "BrandEn");

                    b.HasIndex("NameFa", "BrandFa");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductBOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostPerUnit")
                        .HasColumnType("decimal(12,4)");

                    b.Property<bool>("IsCritical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityRequired")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.HasIndex("ComponentProductId");

                    b.HasIndex("IsCritical");

                    b.HasIndex("ParentProductId");

                    b.HasIndex("Sequence");

                    b.HasIndex("ParentProductId", "ComponentProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductBOM_Parent_Component");

                    b.ToTable("ProductBOMs", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCodes", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductionTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseQuantityProduced")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ProductionCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityProduced")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("SupervisorId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalMaterialCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Unit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionDate");

                    b.HasIndex("Status");

                    b.HasIndex("ProductId", "ProductionDate");

                    b.HasIndex("Status", "ProductionDate");

                    b.ToTable("ProductionTransactions", (string)null);
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Location", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.ProductionTransaction", "ProductionTransaction")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductionTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BatchIQ.Domain.Entities.Location", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromLocation");

                    b.Navigation("Product");

                    b.Navigation("ProductionTransaction");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Location", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Location", "ParentLocation")
                        .WithMany("Children")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductBOM", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Product", "ComponentProduct")
                        .WithMany("UsedInProducts")
                        .HasForeignKey("ComponentProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.Product", "ParentProduct")
                        .WithMany("Components")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentProduct");

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductCode", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany("Codes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductionTransaction", b =>
                {
                    b.HasOne("BatchIQ.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatchIQ.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Location", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.Product", b =>
                {
                    b.Navigation("Codes");

                    b.Navigation("Components");

                    b.Navigation("UsedInProducts");
                });

            modelBuilder.Entity("BatchIQ.Domain.Entities.ProductionTransaction", b =>
                {
                    b.Navigation("InventoryTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
